#!/usr/bin/env bash
# Debugging apache

# Start Apache service
sudo service apache2 start

# Check if Apache is running
if pgrep -x "apache2" > /dev/null; then
    echo "apache2 is running"
else
    echo "apache2 is not running"
fi
